CREATE TABLE dim_supplier_v1
(
    supplier_id TEXT PRIMARY KEY,
    supplier_code TEXT,
    tenant_id TEXT NOT NULL,
    legal_name TEXT NOT NULL,
    dba_name TEXT,
    country TEXT,
    region TEXT,
    address_line1 TEXT,
    address_line2 TEXT,
    city TEXT,
    state TEXT,
    postal_code TEXT,
    contact_email TEXT,
    contact_phone TEXT,
    preferred_currency TEXT,
    incoterms TEXT,
    lead_time_days_avg INTEGER,
    lead_time_days_p95 INTEGER,
    on_time_delivery_rate REAL,
    defect_rate_ppm INTEGER,
    capacity_units_per_week INTEGER,
    risk_score REAL,
    financial_risk_tier TEXT,
    certifications TEXT,
    compliance_flags TEXT,
    approved_status TEXT,
    contracts TEXT,
    terms_version TEXT,
    lat REAL,
    lon REAL,
    data_source TEXT,
    source_timestamp DATETIME,
    ingestion_timestamp DATETIME,
    schema_version TEXT
);


CREATE TABLE dim_part_v1
(
    part_id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    part_number TEXT NOT NULL,
    description TEXT NOT NULL,
    category TEXT,
    lifecycle_status TEXT,
    uom TEXT,
    spec_hash TEXT,
    bom_compatibility TEXT,
    default_supplier_id TEXT,
    qualified_supplier_ids TEXT,
    unit_cost REAL,
    moq INTEGER,
    lead_time_days_avg INTEGER,
    lead_time_days_p95 INTEGER,
    quality_grade TEXT,
    compliance_flags TEXT,
    hazard_class TEXT,
    last_price_change DATE,
    data_source TEXT,
    source_timestamp DATETIME,
    ingestion_timestamp DATETIME,
    schema_version TEXT,
    FOREIGN KEY(default_supplier_id) REFERENCES dim_supplier_v1(supplier_id)
);

